version: '3.4'

services:
  shoponcore.orders.app:
    image: ${DOCKER_REGISTRY}shoponcoreordersapp
    build:
      context: .
      dockerfile: ShopOnCore.Orders.App/Dockerfile
    links:
      - redis_db
      - rabbit_queue

  shoponcore.web:
    image: ${DOCKER_REGISTRY}shoponcoreweb
    build:
      context: .
      dockerfile: ShopOnCore.Web/Dockerfile
    links:
      - redis_db
      - rabbit_queue

  redis_db:
    image: "redis:alpine"

  rabbit_queue:
    image: "rabbitmq:3-management"
    hostname: "rabbit_queue"
    environment:
      RABBITMQ_ERLANG_COOKIE: "ALKJDLKJEIKDVIEHJHDL"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: "rabbit_queue"
